
version: "3.8"
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  node1:
    build:
      context: ..
      dockerfile: docker/Dockerfile.node
    environment:
      NODE_ID: n1
      HTTP_PORT: 8001
      METRICS_PORT: 9001
      SELF_URL: http://node1:8001
      PEERS: http://node2:8002,http://node3:8003
      REDIS_URL: redis://redis:6379/0
      QUORUM: 2
      CLUSTER_NAME: demo
    depends_on: [redis]
    ports:
      - "8001:8001"
      - "9001:9001"
  node2:
    build:
      context: ..
      dockerfile: docker/Dockerfile.node
    environment:
      NODE_ID: n2
      HTTP_PORT: 8002
      METRICS_PORT: 9002
      SELF_URL: http://node2:8002
      PEERS: http://node1:8001,http://node3:8003
      REDIS_URL: redis://redis:6379/0
      QUORUM: 2
      CLUSTER_NAME: demo
    depends_on: [redis]
    ports:
      - "8002:8002"
      - "9002:9002"
  node3:
    build:
      context: ..
      dockerfile: docker/Dockerfile.node
    environment:
      NODE_ID: n3
      HTTP_PORT: 8003
      METRICS_PORT: 9003
      SELF_URL: http://node3:8003
      PEERS: http://node1:8001,http://node2:8002
      REDIS_URL: redis://redis:6379/0
      QUORUM: 2
      CLUSTER_NAME: demo
    depends_on: [redis]
    ports:
      - "8003:8003"
      - "9003:9003"
